### ISSUE TITLE
Can't run on droidian phosh

### ISSUE THREAD

**Issue by who53** [catacombing/tzompantli#37]
I am trying to run it on droidian (which use libhybris and halium), with phosh

thread 'main' panicked at src/main.rs:230:22:
Failed to create EGL surface: Error { raw_code: Some(12292), raw_os_message: None, kind: BadAttribute }

Same error is in kumo, since they use same sort of rendering logic
As far as I can understand any with gles2 rendering should work but these doesn't.

I seriously want to use your apps. Please tell me if you need any more logs or you don't want to target devices which are not running on mainline :( .

**Comment by chrisduerr** [comment]
Unfortunately I have no clue how libhybris and halium work, but all these applications work on the PP which only supports gles2. So I don't think OpenGL version is the issue.

The error indicates that the EGL surface couldn't be created, so I'm curious if you're having issues with any other OpenGL applications. Could you try running glxinfo and ideally maybe even Alacritty? If Alacritty works, then I should be able to make this work too.

**Comment by who53** [comment]
Same error on alacritty :( 

GTK4, QML apps with gles2 rendering works fine.

glxinfo > https://0x0.st/XgQ0.txt

A patched wlroots is used to run phoc/phosh with android hwcomposer backend so we might be missing something ig.

**Comment by chrisduerr** [comment]
I know very little about how halium works, but I know someone else is also trying to write a WPEWebKit browser and they're working on adding support to WPEWebKit because apparently it's something that needs to be explicitly supported.

So if GTK and Qt work, it might just be because someone went through the effort of adding support for libhybris/halium to those toolkits.

Since there are a good chunk of phones that rely on this hack, it would be cool to support of course, but I'm personally only interested in mainline Linux phones. So unless someone else who knows what they're doing sends a patch, it's unlikely this will be supported I think.
